server:
  port: 8080
spring:
  application:
    name: crud-kotlin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_PASSWORD:jdbc:postgresql://localhost:5432/crud_kotlin}
    username: ${POSTGRES_USER:kotlin}
    password: ${POSTGRES_PASSWORD:secret}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    driver-class-name: ${spring.datasource.driver-class-name}
    enabled: true
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
